# coding: utf-8

"""
    Umschlag OpenAPI

    API definition for Umschlag  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import umschlag
from umschlag.api.user_api import UserApi  # noqa: E501
from umschlag.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = umschlag.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_append_user_to_team(self):
        """Test case for append_user_to_team

        Assign a team to user  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a new user  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a specific user  # noqa: E501
        """
        pass

    def test_delete_user_from_team(self):
        """Test case for delete_user_from_team

        Remove a team from user  # noqa: E501
        """
        pass

    def test_list_user_teams(self):
        """Test case for list_user_teams

        Fetch all teams assigned to user  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        Fetch all available users  # noqa: E501
        """
        pass

    def test_permit_user_team(self):
        """Test case for permit_user_team

        Update team perms for user  # noqa: E501
        """
        pass

    def test_show_user(self):
        """Test case for show_user

        Fetch a specific user  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a specific user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
