# coding: utf-8

"""
    Umschlag OpenAPI

    API definition for Umschlag  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import umschlag
from umschlag.models.team_user_params import TeamUserParams  # noqa: E501
from umschlag.rest import ApiException


class TestTeamUserParams(unittest.TestCase):
    """TeamUserParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamUserParams(self):
        """Test TeamUserParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = umschlag.models.team_user_params.TeamUserParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
