---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: webhippie/python:latest
  pull: always
  commands:
  - pip3 install -r dev-requirements.txt
  - flake8 setup.py umschlag tests
  - nosetests --with-coverage --cover-package umschlag -v

- name: release
  image: plugins/pypi:1
  pull: always
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
  when:
    event:
    - tag
  depends_on:
  - test

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure
  depends_on:
  - test
  - release

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
