workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-python

branches:
  - master

pipeline:
  sdk-test:
    image: webhippie/python:latest
    pull: true
    commands:
      - pip3 install -r dev-requirements.txt
      - flake8 setup.py umschlag tests
      - nosetests --with-coverage --cover-package umschlag -v

  # TODO: do some automated release upload
  # sdk-release:
  #   image:
  #   pull: true
  #   when:
  #     event: [ tag ]
  #     branch: master

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push, tag ]
      status: [ changed, failure ]
