---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: flake8
  image: webhippie/python:latest
  pull: always
  environment:
    PY_COLORS: 1
  commands:
  - tox -e flake8

- name: test
  image: webhippie/python:latest
  pull: always
  environment:
    PY_COLORS: 1
  commands:
  - tox -e py3

- name: codacy
  image: webhippie/python:latest
  pull: always
  environment:
    PY_COLORS: 1
    CODACY_PROJECT_TOKEN:
      from_secret: codacy_token
  commands:
  - tox -e codacy
  when:
    instance:
    - cloud.drone.io

- name: release
  image: plugins/pypi:1
  pull: always
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
  when:
    event:
    - tag

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
